source/rails_challenge/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :credit_card_charges
  root to: "credit_card_charges#index"

end

source/rails_challenge/app/models/credit_card_charge.rb
class CreditCardCharge < ActiveRecord::Base
end

source/rails_challenge/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

source/rails_challenge/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

source/rails_challenge/app/controllers/credit_card_charges_controller.rb
class CreditCardChargesController < ApplicationController
  before_action :set_credit_card_charge, only: [:show, :edit, :update, :destroy]

  # GET /credit_card_charges
  # GET /credit_card_charges.json
  def index
    @credit_card_charges = CreditCardCharge.all
  end

  # GET /credit_card_charges/1
  # GET /credit_card_charges/1.json
  def show
  end

  # GET /credit_card_charges/new
  def new
    @credit_card_charge = CreditCardCharge.new
  end

  # GET /credit_card_charges/1/edit
  def edit
  end

  # POST /credit_card_charges
  # POST /credit_card_charges.json
  def create
    @credit_card_charge = CreditCardCharge.new(credit_card_charge_params)

    respond_to do |format|
      if @credit_card_charge.save
        format.html { redirect_to @credit_card_charge, notice: 'Credit card charge was successfully created.' }
        format.json { render :show, status: :created, location: @credit_card_charge }
      else
        format.html { render :new }
        format.json { render json: @credit_card_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_card_charges/1
  # PATCH/PUT /credit_card_charges/1.json
  def update
    respond_to do |format|
      if @credit_card_charge.update(credit_card_charge_params)
        format.html { redirect_to @credit_card_charge, notice: 'Credit card charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_card_charge }
      else
        format.html { render :edit }
        format.json { render json: @credit_card_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_card_charges/1
  # DELETE /credit_card_charges/1.json
  def destroy
    @credit_card_charge.destroy
    respond_to do |format|
      format.html { redirect_to credit_card_charges_url, notice: 'Credit card charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card_charge
      @credit_card_charge = CreditCardCharge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_charge_params
      params.require(:credit_card_charge).permit(:id, :created, :paid, :amount, :currency, :refunded, :disputed)
    end
end

source/rails_challenge/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  current_user
  user_signed_in?
  user_session

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /  users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

source/rails_challenge/app/helpers/application_helper.rb
module ApplicationHelper
end

source/rails_challenge/app/helpers/credit_card_charges_helper.rb
module CreditCardChargesHelper
end

source/rails_challenge/app/helpers/users_helper.rb
module UsersHelper
end

source/rails_challenge/app/views/credit_card_charges/_form.html.erb
<%= form_for(@credit_card_charge) do |f| %>
  <% if @credit_card_charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card_charge.errors.count, "error") %> prohibited this credit_card_charge from being saved:</h2>

      <ul>
      <% @credit_card_charge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :created %><br>
    <%= f.number_field :created %>
  </div>
  <div class="field">
    <%= f.label :paid %><br>
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :refunded %><br>
    <%= f.check_box :refunded %>
  </div>
  <div class="field">
    <%= f.label :disputed %><br>
    <%= f.check_box :disputed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

source/rails_challenge/app/views/credit_card_charges/edit.html.erb
<h1>Editing Credit Card Charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_card_charge %> |
<%= link_to 'Back', credit_card_charges_path %>

source/rails_challenge/app/views/credit_card_charges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Credit Card Charges</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Created</th>
      <th>Paid</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Refunded</th>
      <th>Disputed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_card_charges.each do |credit_card_charge| %>
      <tr>
        <td><%= credit_card_charge.id %></td>
        <td><%= credit_card_charge.created %></td>
        <td><%= credit_card_charge.paid %></td>
        <td><%= credit_card_charge.amount %></td>
        <td><%= credit_card_charge.currency %></td>
        <td><%= credit_card_charge.refunded %></td>
        <td><%= credit_card_charge.disputed %></td>
        <td><%= link_to 'Show', credit_card_charge %></td>
        <td><%= link_to 'Edit', edit_credit_card_charge_path(credit_card_charge) %></td>
        <td><%= link_to 'Destroy', credit_card_charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit card charge', new_credit_card_charge_path %>

source/rails_challenge/app/views/credit_card_charges/new.html.erb
<h1>New Credit Card Charge</h1>

<%= render 'form' %>

<%= link_to 'Back', credit_card_charges_path %>

source/rails_challenge/app/views/credit_card_charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @credit_card_charge.id %>
</p>

<p>
  <strong>Created:</strong>
  <%= @credit_card_charge.created %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @credit_card_charge.paid %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @credit_card_charge.amount %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @credit_card_charge.currency %>
</p>

<p>
  <strong>Refunded:</strong>
  <%= @credit_card_charge.refunded %>
</p>

<p>
  <strong>Disputed:</strong>
  <%= @credit_card_charge.disputed %>
</p>

<%= link_to 'Edit', edit_credit_card_charge_path(@credit_card_charge) %> |
<%= link_to 'Back', credit_card_charges_path %>

source/rails_challenge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

source/rails_challenge/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

source/rails_challenge/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

source/rails_challenge/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

source/rails_challenge/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

source/rails_challenge/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>